version: 2
jobs:
  build:
    docker:
      - image: myrjola/react-native-android-appium:v0.5
    working_directory: "/root/beersunderx"
    environment:
      QEMU_AUDIO_DRV: none
      LC_ALL: "C.UTF-8"
    steps:
      - checkout
      - restore_cache:
          key: beersunderx-node-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Create artifacts directory
          command: mkdir -p artifacts
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: beersunderx-node-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache/yarn
            - /usr/local/lib/node_modules/
      - restore_cache:
          key: beersunderx-{{ .Branch }}-jest
      - run:
          name: NPM Test
          command: npm test
      - save_cache:
          key: beersunderx-{{ .Branch }}-jest-{{ epoch }}
          paths:
            - .jest-cache
      - run:
          name: Create integration test keystore
          command: |
            cd android/app && \
              keytool -genkey -v -keystore beersunderx.keystore \
                -alias beersunderx -keyalg RSA -keysize 2048 \
                -keypass android -storepass android \
                -dname "CN=Android Integrationtest,O=BeersUnderX,C=SE"
      - run:
          name: Set the correct signing settings
          command: |
            cp android/app/local.properties.integration \
               android/app/local.properties
      - restore_cache:
          key: beersunderx-gradle-{{ .Branch }}-{{ checksum "android/app/build.gradle" }}
      - run:
          name: Bundle assets manually to save memory
          command: |
            stty rows 50 cols 80
            react-native bundle --platform android --dev false \
              --entry-file index.android.js \
              --bundle-output android/app/build/intermediates/assets/release/index.android.bundle \
              --assets-dest android/app/build/intermediates/res/merged/release/ \
              --verbose
      - run:
          name: Assemble release APK
          command: cd android && ./gradlew assembleRelease --info -x bundleReleaseJsAndAssets
          environment:
            TERM: dumb
      - save_cache:
          key: beersunderx-gradle-{{ .Branch }}-{{ checksum "android/app/build.gradle" }}
          paths:
            - ~/.gradle
            - android/build
            - android/app/build
      - store_artifacts:
          path: artifacts
