version: 2
jobs:
  build:
    docker:
      - image: node:7.4.0
    working_directory: "/root/beersunderx"
    steps:
      - checkout
      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Create artifacts directory
          command: mkdir -p artifacts
      - run:
          name: Install Yarn
          command: npm install --global yarn
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: NPM Test
          command: npm test
      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - .jest-cache
            - ~/.npm
            - ~/.cache/yarn
            - /usr/local/lib/node_modules/
      - store_artifacts:
          path: artifacts
