version: 2
jobs:
  build:
    docker:
      - image: node:7.4.0
    working_directory: ~/beersunderx
    steps:
      - checkout
      - run:
          name: Create artifacts directory
          command: mkdir -p ~/beersunderx/artifacts
      - run:
          name: Install Yarn
          command: npm install --global yarn
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: NPM Test
          command: npm test
      - store_artifacts:
          path: ~/beersunderx/artifacts
