fastlane_version "2.28.5"

default_platform :ios

platform :ios do
  desc "Submit a new Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :alpha do
    sigh
    increment_build_number(xcodeproj: './ios/neartobeer.xcodeproj') # Increment the build number
    gym(scheme: "Near to beer", project: './ios/neartobeer.xcodeproj') # Build the app
    pilot(skip_submission: true) # Upload the app to TestFlight
  end
end

platform :android do
  desc "Submit a new Alpha Build to Play Store"
  lane :alpha do
    gradle(task: "assemble", build_type: "Release", project_dir: "android/") # Build the Release APK
    supply(track: "alpha", apk: "android/app/build/outputs/apk/app-release.apk") # Upload the APK to the Play Store (alpha)
  end

  lane :screenshots do
    gradle(task: "assemble", build_type: "Debug", project_dir: "android/") # Build the debug apk
    gradle(task: "installDebugAndroidTest", project_dir: "android/") # Build the tests
    screengrab
  end

  lane :bump_version_code do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/

    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s

    f = File.new(path, 'w')
    f.write(s)
    f.close
  end
end